name: Publish
on:
  create:
    tags:
      - 'v\d\.\d\.\d'
      - 'v\d\.\d\.\d-(dev|rc)\d'
jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          find -type l -exec bash -c 'ln -f "$(readlink -m "$0")" "$0"' {} \;
          poetry build --format=sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
