---
name: Publish dev
on: push
#  create:
#    branches:
#      - main
#    tags:
#      - 'v*'

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
#    environment: release
#    environment:
#      name: pypi
#      url: https://test.pypi.org/p/vmittal-focus
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true